### ISSUE TITLE
Invitation to join the Highlight.js grammar-maintainers team

### ISSUE THREAD

**Issue by joshgoebel** [leanprover-community/highlightjs-lean#6]
Re: Invitation to join the Highlight.js grammar-maintainers team

I'd like to invite the grammar maintainer/maintainers to our `@highlightjs/grammar-maintainers` Team... this team is used to ping grammar maintainers about big upcoming changes or get their feedback on things that may affect them in the future. 

But I don't know who to invite... can you assist?

**Comment by bryangingechen** [comment]
You can invite me and @PatrickMassot for now.

**Comment by joshgoebel** [comment]
Done.
